### ISSUE TITLE
On Spring 3.1.1 migration receiving 401 response code

### ISSUE THREAD

**Issue by Manikandan-c** [quantics-io/multitenant-oauth2-spring-boot-starter#11]
jpaPropertiesMap.put(Environment.MULTI_TENANT,MultiTenancyStrategy.SCHEMA );

MULTI_TENANT & ,MultiTenancyStrategy.SCHEMA are deprecated, after commenting this line also not working receiving 401 response code.

**Comment by jeenec** [comment]
Any Updates on springboot 3

**Comment by jomatt** [comment]
@Manikandan-c @jeenec I have updated the library to Java 17 and Spring Boot 3.1.5 in #13. I'm currently testing it and would also appreciate your feedback to the update. Please let me know if you encounter any issues. If everything works well, I will release version `0.4` soon.

**Comment by Shanmugame0611** [comment]
@jomatt After adding this dependency in local maven. Created a new sample spring boot application with new version as per the your code changes and copied the files of your sample project files but while running the application facing the below issue.

Parameter 0 of method entityManagerFactory in com.example.demo.config.**MultiTenantSchemaHibernateConfiguration** required a bean of type 'javax.sql.DataSource' that could not be found. 

![image](https://github.com/quantics-io/multitenant-oauth2-spring-boot-starter/assets/140100020/073e4d42-08fa-4b93-97ff-c1037bef3e08)

**Comment by Manikandan-c** [comment]
@jomatt : I had tested the latest version 0.4 Library, with the given sample multinenant application, after some small changes its working as expected

**Comment by jeenec** [comment]
> @jomatt : I had tested the latest version 0.4 Library, with the given sample multinenant application, after some small changes its working as expected

@Manikandan-c  How did you included the 0.4 library 
is by pom.xml or imported the jar file from this source code?

**Comment by Manikandan-c** [comment]
@jomatt Imported from source, and installed jar locally then access via pom.xml file

**Comment by jeenec** [comment]
@jomatt  : I had tested the latest version 0.4 Library, with the given sample multitenant application
its working as expected

**Comment by jeebendu** [comment]
@jomatt  latest change for spring boot 3 for this plugin was tested and it's working fine 

We can go for 0.4 release

**Comment by jeenec** [comment]
@jomatt 
in SecurityConfig.java 
```
.requestMatchers(
                                "/swagger-resources/**",
                                "/swagger-ui.html",
                                "/swagger-ui/**",
                                "/v3/api-docs/**",
                                "/webjars/**"
                        ).permitAll()
```
Still we are facing the issue to access swagger UI  without authentication
its coming as 401

@Manikandan-c 
Did you face the same issue ?

**Comment by Manikandan-c** [comment]
@jeebendu I did checked for swagger, will let you know soon

**Comment by jomatt** [comment]
> @jomatt in SecurityConfig.java
> 
> ```
> .requestMatchers(
>                                 "/swagger-resources/**",
>                                 "/swagger-ui.html",
>                                 "/swagger-ui/**",
>                                 "/v3/api-docs/**",
>                                 "/webjars/**"
>                         ).permitAll()
> ```
> 
> Still we are facing the issue to access swagger UI without authentication its coming as 401
> 
> @Manikandan-c Did you face the same issue ?

@jeenec Thanks for noting this. I updated both the PR #13 and the PR in https://github.com/jomatt/spring-boot-multitenant-sample/pull/6 to verify the changes. Accessing the whitelisted URL paths (incl. Swagger UI) should now work correctly without requiring authentication.

**Comment by jeenec** [comment]
@jomatt 
swagger public url issue tested and it was working as expected.

Also can you update spring boot version to 3.2.0 as this is latest released on 23 Nov 2023

**Comment by jomatt** [comment]
@jeenec I updated both PRs to the latest Spring Boot version 3.2.0
