### ISSUE TITLE
Application not running when adding the starter dependency

### ISSUE THREAD

**Issue by siddhuoo7** [quantics-io/multitenant-oauth2-spring-boot-starter#7]
![image](https://user-images.githubusercontent.com/43318941/205504350-9854c2bc-7dba-4c0a-b468-ac6ff8db33dd.png)

getting this error while compiling you starter jar and use in my application.

just run using **mvn  clean install** .

**Comment by jomatt** [comment]
@siddhuoo7 Could you please provide some additional details for this issue?

Which spring-boot version are you using? Do you have an example project that I could check to reproduce the issue?
