### ISSUE TITLE
FlywayConfig 

### ISSUE THREAD

**Issue by amadeuscam** [quantics-io/multitenant-oauth2-spring-boot-starter#9]
First of all, I thank you for sharing your knowledge with us and for the work for having written this blog that has been very useful to me, I have followed all the steps of the blog but in the last point it is failing me with this message
`Parameter 0 of method tenantsFlyway in com.amadeuscam.MultiTenantTestApp.jwt.config.FlywayConfig required a bean of type 'io.quantics.multitenant.tenantdetails.TenantSchemaDetailsService' that could not be found.
`
`Action:Consider defining a bean of type 'io.quantics.multitenant.tenantdetails.TenantSchemaDetailsService' in your configuration.`

It will be because the Service annotation to that class is missing in the library?
![2023-02-27_06-50](https://user-images.githubusercontent.com/7137827/221485011-de077330-09ca-424d-b201-6cff10f277fc.png)
Thank you!!

**Comment by jomatt** [comment]
Hi @amadeuscam! Thanks for the feedback - I'm happy that the blog articles and this library are useful for you.

From a first glance, it seems like you don't have a `TenantSchemaDetailsService` bean. The library just provides the interface for the service, but you need to define your own bean that implements `TenantSchemaDetailsService`. Once you have declared and exposed it as a `@Service`, the library should automatically pick it up and run the migrations for each tenant.

You can find an example implementation here: https://github.com/jomatt/spring-boot-multitenant-sample/blob/main/src/main/java/io/jomatt/multitenant/sample/common/tenant/TenantService.java

**Comment by amadeuscam** [comment]
Perfect, thanks !
